bootstrap: adds bootstrap stuff for ubuntu for work

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+# sudo check
+echo "Checking sudo capabilities"
+sudo ls &> /dev/null
+if [ $? -ne 0 ]
+then
+  echo "Unable to get sudo, are you on the naughty list?"
+  exit 1
+fi
 export OS=$(cat /etc/os-release | grep -E "\bID\b" | cut -d'=' -f2)
 if [[ $OS == "arch" ]];
 then
@@ -18,3 +26,9 @@ then
   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
 fi
 
+if [[ -x $(which nvim) ]]
+then
+  git clone https://github.com/alemuller/tree-sitter-vhdl.git ~/.local/share/tree-sitter/tree-sitter-vhdl
+  git clone --depth 1 https://github.com/wbthomason/packer.nvim \
+    ~/.local/share/nvim/site/pack/packer/start/packer.nvim
+fi
